### ISSUE TITLE
Allowing posting raw (unstringified) messages

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/promise-worker#1]
Occasionally it's useful to be able to directly `postMessage()` for Blobs/ArrayBuffers/Dates/etc. It would be nice if the API could support both.

One idea: split messages explicitly into different types, as an optional first argument before the message. So sending a raw message:

```js
promiseWorker.postRawMessage('my_raw_id', blob);
```

And receiving a raw message from the worker:

```js
registerRaw({
  'my_raw_id': function () {
    /* ... */
  }
})
```

So you would be able to post send and receive raw messages, in any combination you choose.

This would require allowing users to call `register` and `registerRaw` twice. It would also require some switching to support message types.

**Comment by francescoagati** [comment]
what about using channel message api? 
https://developer.mozilla.org/en-US/docs/Web/API/Channel_Messaging_API/Using_channel_messaging

**Comment by nolanlawson** [comment]
When you communicate with a web worker, it _is_ a channel. There's just a single one.

**Comment by Sorceror** [comment]
Wouldn't be better to allow set custom _reviver_ and _replacer_ for `JSON.parse()` and `JSON.stringify()` respectively? That would allow to map and resolve whatever type is needed (like _UInt32Array_ and other typed arrays in my case).

**Comment by nolanlawson** [comment]
@Sorceror I intentionally made this library as simple as possible, without any extra options or configuration. The idea is that interested parties can fork the code and make it do whatever they want. :)

Ultimately I think there are too many ways of handling worker messages, so I'd prefer just to keep this library small and focused. Gonna close this issue for now.

**Comment by viskin** [comment]
As mentioned in #13, I forked a library to [promise-worker-transferable](https://github.com/terikon/promise-worker-transferable).
It completely eliminates JSON.parse when passing messages, and behaves (mostly) just as plain Worker.postMessage.
Blob transfer is possible, as well as providing transfer list. I use it to quickly move imageData.

**Comment by zhanghaowx** [comment]
It would be a good if can support transferable object
