### ISSUE TITLE
Sample on README worker.addEventListener is not a function

### ISSUE THREAD

**Issue by opiepj** [nolanlawson/promise-worker#15]
Using the sample on the readme I get this error.

I'm using webpack and I load in my code like so:

client.js

``` js
let PromiseWorker = require('promise-worker');
let worker = require('worker!app/workers/simple-worker');
let promiseWorker = new PromiseWorker(worker);

promiseWorker.postMessage('ping').then(function (response) {
  // handle response
  console.log(response)
}).catch(function (error) {
  // handle error
  console.log(error);
});
```

simple-worker.js

``` js
var registerPromiseWorker = require('promise-worker/register');

registerPromiseWorker(function (message) {
  return 'pong';
});
```

Returns

```
index.js:46 Uncaught TypeError: worker.addEventListener is not a function
```

promise-worker/index.js line  46

**Comment by nolanlawson** [comment]
This looks like an error in the worker loader you're using with Webpack. Are you certain that it returns a valid web worker object? All web workers have an `addEventListener` method.

**Comment by opiepj** [comment]
It returns a wrapper so I would need to do worker.worker.addEventListener. Closing this as it is an inconsistency with my loader.
