### ISSUE TITLE
Communication initiated by worker

### ISSUE THREAD

**Issue by dumbmatter** [nolanlawson/promise-worker#18]
This package lets you send a request from the browser to the worker, easily respond to that from the worker, and get the response returned in a promise in the browser.

What if I also want to be able to send a request from the worker to the browser, easily respond to that from the browser, and get the response returned in a promise in the worker? Couldn't that be done by an equivalent mechanism?

Seems like it'd work, but I've never used Web Workers much, so maybe this is a really bad idea for some reason.

If it's not a really bad idea, would you be interested in a PR, or is that different enough to just be another project?

**Comment by dumbmatter** [comment]
I figure you probably don't want a PR, and I don't really want to mess around with supporting Service Workers since my use case doesn't need them now. So I made https://github.com/dumbmatter/promise-worker-bi

**Comment by nolanlawson** [comment]
Yup, I never really considered the use case of the worker initiating the conversation, also you're quite right that I intended to keep this module pretty small and focused, so forking the project was a good choice. Nice work! :)

**Comment by oychao** [comment]
This is exactly what I need, thank you so much.
