### ISSUE TITLE
Send error stack traces to the main thread

### ISSUE THREAD

**Issue by dumbmatter** [nolanlawson/promise-worker#23]
The README currently says:

> Note that stacktraces cannot be sent from the worker to the main thread

I'm guessing you wrote that because listening to `Worker.onerror` gets an `ErrorEvent` object, but the `error` property is always null for some reason, and because you can't send error objects over `postMessage`.

However in the worker (either via try/catch of `self.onerror`), you can see the stack trace. And `Error.stack` is just a string, so even though you can't send the actual `Error` back via `self.postMessage`, you can send the stack.

This requires some extra complexity, because you need to distinguish between different types of messages sent from promise-worker itself, similar to the "multi-type messages" example in the README, but working internally.

Even better, you can send all the properties of the error back, and then assign them all to a new error object in the main thread. Then it is nearly transparent to the user, it seems as if the real error object has been transferred. Except... if you use source maps, they won't work. You can still use source maps manually, of course. And even better, third-party error tracking services like https://www.bugsnag.com/ are smart enough to apply the source maps to your "fake" error objects automatically!

All of this is implemented in [my fork of this project](https://github.com/dumbmatter/promise-worker-bi/). I'm unlikely to send a PR here because I don't know if you want the additional message-passing complexity, and because my fork has substantially diverged from yours at this point. But I figured I'd leave a note here in case any users were wondering about error handling.

**Comment by nolanlawson** [comment]
Thanks, this is good to know. I guess I meant that stacktraces cannot be sent to the main thread in a way that easily allows debugging in browser Dev Tools (although who knows perhaps I'm wrong about that as well).

I'm currently not actively maintaining this project, but I would accept a PR to fix this particular issue assuming it's not a lot of extra code or complexity! :)

**Comment by nolanlawson** [comment]
Closing old issues, I think this would be worthwhile but I may not get around to it
