### ISSUE TITLE
Is localStorage not supported ??

### ISSUE THREAD

**Issue by subhranshudas** [nolanlawson/promise-worker#25]
I am importing a module called `Storage.js` in my Web Worker. This module uses `localStorage` internally in its methods. 

I get error when my Worker calls methods of `Storage.js` as `localStorage` not defined.

Is there no way to use external modules in web worker which use `localStorage`.

I checked out https://nolanlawson.github.io/html5workertest/ where it tells we can use `indexedDB`, but my question is what if some external modules which i am using uses `localStorage`, is it out of question?

Also i checked out `localForage` where we can set the driver to any mechanism we want. How does `indexedDB` compares to `localStorage` or other web storage mechanisms in terms of **performance**. Any definitive sources are appreciated.

Thanks.

**Comment by nolanlawson** [comment]
Correct, Web Workers do not have access to LocalStorage. Unfortunately you will have to ask the module author to change the code to support IndexedDB, use an in-memory store, or some other workaround.

**Comment by subhranshudas** [comment]
@nolanlawson thanks for the reply!!
i have few lingering questions, but will direct them in the localForage thread https://github.com/localForage/localForage/issues/823#issuecomment-392231601

**Comment by subhranshudas** [comment]
@nolanlawson quick question - is indexedDB supported in web workers in safari
https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Functions_and_classes_available_to_workers says otherwise, where as your table shows supported!!

**Comment by nolanlawson** [comment]
The MDN docs are probably out of date. html5workertest uses automated testing to test a real browser.
