### ISSUE TITLE
disable logging worker exceptions to the console

### ISSUE THREAD

**Issue by ericprud** [nolanlawson/promise-worker#33]
The current worker handler logs exceptions to the console. Given that exception transfer between the worker and the client is really smooth, I think many folks would want to leverage it, but may not want to dump dirty laundry on the console.
```js
            function registerPromiseWorker(callback) {
                function postOutgoingMessage(e, messageId, error, result) {
                    if (error) {
                        if (typeof console !== 'undefined' && 'error'in console) {
                            // This is to make errors easier to debug. I think it's important
                            // enough to just leave here without giving the user an option
                            // to silence it.
                            console.error('Worker caught an error:', error)
                        }
```
A switch would allow workers to debug by default but turn it off if they don't want it.

**Comment by nolanlawson** [comment]
I think console logging is the concern of the application. It can be handled in the bundling/minification process, e.g. with terser ([sample code](https://github.com/nolanlawson/pinafore/blob/f09e1bd97585acd46310cb4196b5f60d461076a7/bin/terserOptions.js#L4-L8)).

Lots of JS libraries may log/error/warn to the console for a variety of reasons; rather than asking every individual library to have an option for this, I think it should just be up to the app author. Thanks for opening the issue though!

**Comment by ericprud** [comment]
That terser work-around means the worker can't do any logging. A test like
```if (registerPromiseWorker.logExceptions && typeof console !== 'undefined' && 'error' in console) ```
would allow the worker to turn it off:
```registerPromiseWorker.logExceptions = false```

BTW, I use `pseudo-worker` in node ([my imp of `importScripts`](https://github.com/shexSpec/shex.js/blob/web-worker/test/browser-test.js#L689-L701) is a bit precarious but jsdom doesn't support workers at all and I wanted to be able to test). So in principle, you could use promise-worker in node where the terser hack wouldn't be available.

**Comment by nolanlawson** [comment]
With the terser workaround, you can conditionally disable `console.warn`/`console.log`/`console.error`/etc. It doesn't have to disable all of `console`.

In Node, you can also work around this by just overriding `console.error` function.

I understand the need for this, but I just feel that it complicates the API a bit too much relative to the gains, and especially given that workarounds exist. To my original point, lots of libraries use `console`, and it would be a bit awkward if all of them had separate APIs to disable it.

**Comment by ericprud** [comment]
Fair enough. Would it make sense to document these approaches in the README?

**Comment by nolanlawson** [comment]
Sure, makes sense to me!
